- .travis.yml
- build-with-opam.sh
It is now also usable as a build script for use at home.
Joint work with Amin.
> Added continuous integration for OS X.

- bin/prelude.h
- src/verifast1.ml
hi, 
Here is something to add support for long long int. 
It adds (updated when I push): 
- sizeof(long long) which is 8
- llongs predicate int prelude.h (does the same as ints)
> sizeof(long long) and other

- bin/prelude.h
> Add predicate "ullongs"

- src/verifast1.ml
> Add cast from int64 to int32, int16, etc..

- bin/prelude.h
- src/verifast1.ml
> long long arrays: update (1) prelude.h and (2) pointee_tuple according to predicates in prelude.h

- bin/crt.vfmanifest
- bin/prelude.h
Nothing fancy, just something similar to the other ***_inv() lemmas.
> Add llongs_inv and ullongs_inv to prelude.h

- .gitignore
- src/GNUmakefile
It's used by ocamlspot.
https://bitbucket.org/camlspotter/ocamlspot/
> Add make option create *.cmt and *.cmti files.

- src/smtlib.ml
Fixes some problems with the SMTLib code generated when using 
-prover ext_z3, or using another prover with +SMTLIB
When creating a fresh name, the characters ' and # are now escaped,
since they are not allowed in SMTLib symbols [1]. 
Numerals are also escaped since they may not appear at the start of a symbol
The names "store", "select", "NaN", "fp", "div", "repeat", "xor" and "concat"
have been added to the list of reserved words since Z3 reserves them.
Ratios are now printed as (/ a b) instead of a/b.
Some operations had a dot character appended to their associated symbols,
even though that makes them meaningless. The dots have been removed.
[1] http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.0-r10.12.21.pdf
Section 3.1, under 'Symbols'
PS: Sorry for the three commits when it …
> Fix invalid symbols in SMTLib code

- src/verifast1.ml
This is just a skeleton and most likely still contains some mistakes. It should be used as a base to recreate the Java type inference algorithm once more generic functionalities have been added.
> Java type inference skeleton

- bin/crt.vfmanifest
- bin/prelude.h
- examples/mcas/bitops_ex.vfmanifest
I forgot these in #212, sorry.
> Add autolemmas for bool/booleans to/from chars

- .gitignore
- src/SExpressionEmitter.ml
I want to use sexprs for now to export information for debugging purposes. To enable this, I completed some match clauses that were missing.
> A small set of changes

- src/json.ml
- src/json_tests.ml
Pretty printing for json values, which can be useful when debugging
> pretty print json

- README.Linux.md
- README.MacOS.md
- README.Windows.md
> Update build instructions

- src/verify_expr.ml
- tests/cxx/java_like/Account.h
> Disallow calling a method when it's target might be null

- src/cxx_frontend/ast_exporter/DeclSerializer.cpp
- src/verifast.ml
- src/verify_expr.ml
- tests/cxx/constructors.cpp
Adds support for delegating constructors.
> Delegating constructors

- src/SExpressionEmitter.ml
- src/SExpressionEmitter.mli
- src/ast.ml
- src/cxx_frontend/ast_exporter/ExprSerializer.cpp
- src/cxx_frontend/ast_exporter/NodeSerializer.h
- src/cxx_frontend/ast_exporter/TypeSerializer.cpp
- src/cxx_frontend/cxx_ast_translator.ml
- src/cxx_frontend/stubs/stubs_ast.capnp
- src/verifast.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/cxx/inheritance/diamond.cpp
- tests/cxx/inheritance/multiple_inheritance.cpp
- tests/cxx/inheritance/single_inheritance.cpp
- tests/cxx/lvalue_refs.cpp
- testsuite.mysh
Multiple inheritance without virtual bases or methods
> C++ multiple inheritance

- bin/prelude.h
- src/verifast1.ml
- tests/typeid.c
This will be useful for checking effective types.
> sizeof((pointer)typeid(T)) == sizeof(T)

- examples/busywaiting/clhlock/atomics.h
- examples/busywaiting/clhlock/clhlock.c
- examples/busywaiting/clhlock/clhlock.h
- examples/busywaiting/clhlock/clhlock_as_ticketlock.c
- examples/busywaiting/clhlock/clhlock_as_ticketlock.h
- testsuite.mysh
- WIP clhlock_as_ticketlock
- Finished proof of clhlock_as_ticketlock.c
- clhlock_as_ticketlock.c: Add ack
- WIP clhlock.c (fixed level)
- Proved stronger CLH lock spec (via ticketlock spec)
- testsuite.mysh: Add clhlock_as_ticketlock.c
> Prove stronger CLH lock spec (via ticketlock spec)

- setup-windows.sh
Speeds up running the script repeatedly
> setup-windows.sh: do not re-download/extract

- tests/rust/purely_unsafe/tree.rs
- tests/rust/purely_unsafe/tree2.rs
- testsuite.mysh
- tree.rs: assert all nodes are marked
- tree2.rs: pointer tagging
> tree2.rs: pointer tagging

- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_exporter/src/preprocessor.rs
TODO: Eliminate all ocamlc warnings
> [Refactoring] Eliminate all rustc warnings

- bin/prelude_rust.h
- bin/rust/std/lib.rsspec
- src/assertions.ml
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/verifast.ml
- src/verifast1.ml
- tests/rust/purely_unsafe/pred_fam.rs
- tests/rust/testsuite.mysh
A step towards expressive trait specs
> [Rust] Predicate families (indexed by struct name)

- bin/prelude.h
- src/assertions.ml
- src/frontend/verifast0.ml
- src/verifast.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/generic_structs.c
- testsuite.mysh
By "generic field", I mean a field of a generic struct whose
type is a type parameter.
> Support taking the address of a generic field

- examples/generic_pred_ctors.c
- src/SExpressionEmitter.ml
- src/assertions.ml
- src/frontend/ast.ml
- src/frontend/ocaml_expr_of_ast.ml
- src/frontend/parser.ml
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- src/verifast1.ml
- testsuite.mysh
TODO: Support auto-opening/closing predicates with type parameters
that carry typeids.
> Generic predicate constructors

- examples/generic_pred_ctors.c
- src/assertions.ml
- src/verifast.ml
- src/verify_expr.ml
Also fixes a bug in the way the auto-open/close logic deals with
environments.
> Auto-open/close preds with typeid-carrying tparams

- src/cxx_frontend/stmt_translator.ml
- tests/cxx/non_compound_stmts.cpp
- testsuite.mysh
> [C++] Fix parsing of non-compound stmts

- bin/prelude_rust_core.gh
- bin/rust/std/lib.rsspec
- src/frontend/ast.ml
- src/frontend/verifast0.ml
- src/rust_frontend/rust_fe.ml
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- src/verifast1.ml
- tests/rust/purely_unsafe/httpd.rs
- tests/rust/testsuite.mysh
- tests/rust/unverified/platform/.gitignore
- tests/rust/unverified/platform/Cargo.toml
- tests/rust/unverified/platform/spec/lib.rsspec
- tests/rust/unverified/platform/src/lib.rs
- tests/rust/unverified/platform/src/sockets.rs
Also:
- module-aware name resolution
- const declarations
- structs in .rsspec files
- 'self' as parameter name in .rsspec files
- locals of bodyless struct type are no longer heapified by default
- Generate axiom that for each value s of struct type S, we have
S { f1=s.f1; ...; fN=s.fN } == s
> [Rust] External crates; httpd.rs example

- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- tests/rust/purely_unsafe/httpd.rs
- tests/rust/purely_unsafe/tree.rs
- tests/rust/purely_unsafe/tree2.rs
- tests/rust/purely_unsafe/tree3.rs
- **[Rust] Reconstruct loops**
- **[Rust] Some optimizations in find_loops**
- **[Rust] Enable framing chunks over loops**
> [Rust] Improve translation of loops

- bin/rust/std/lib.rsspec
- src/assertions.ml
- src/frontend/lexer.ml
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/rust/safe_abstraction/deque.rs
- tests/rust/safe_abstraction/deque_i32.rs
- tests/rust/testsuite.mysh
- **[Rust] Generic safe Deque**
- **When consuming**
> [Rust] Generic safe deque

- src/rust_frontend/vf_mir/vf_mir.capnp
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/rust/purely_unsafe/my_option.rs
- tests/rust/testsuite.mysh
> [Rust] Enums

- bin/prelude_rust.h
- src/rust_frontend/vf_mir/vf_mir.capnp
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/purely_unsafe/httpd.rs
- tests/rust/purely_unsafe/my_option.rs
- **[Rust] Generic enums**
- **[Rust] Slices**
> [Rust] Generic enums; slices

- src/SExpressionEmitter.ml
- src/frontend/ast.ml
- src/frontend/ocaml_expr_of_ast.ml
- src/frontend/parser.ml
- src/verifast.ml
- src/verify_expr.ml
- tests/continue.c
- testsuite.mysh
> `continue` statements

- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/mutex_u32.rs
Adds support for public structs that have fields of struct type. These
fields are treated just like other fields.
> [Rust] Support public structs with nested structs

- bin/rust/rust_belt/general.h
- tests/rust/safe_abstraction/deque.rs
- tests/rust/safe_abstraction/generic_pair.rs
Also fixes an unsoundness in share_full_borrow in general.h.
> [Rust] Prove Pair_share_full, Pair::deref_fst_mut

- bin/rust/rust_belt/general.h
- src/rust_frontend/vf_mir/vf_mir.capnp
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
- tests/rust/testsuite.mysh
These are simply added as parameters to S_own,
S_full_borrow_content, and S_share.
TODO:
- Support impl blocks for structs with lifetime parameters.
- Support implementing 'drop' for structs with lifetime parameters.
> [Rust] Structs with lifetime parameters

- src/SExpressionEmitter.ml
- src/frontend/ast.ml
- src/frontend/ocaml_expr_of_ast.ml
- src/frontend/parser.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/comma_expr.c
- testsuite.mysh
> Comma operator

- src/frontend/util.ml
- src/vfide/vfide.ml
Thanks to Thomas Baar for suggesting this feature.
> vfide: Add "Open Recent" menu

- bin/rust/list.rsspec
- bin/rust/std/lib.rsspec
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/purely_unsafe/strlen.rs
Also:
- Add support for offset_from
- Reformat vf_mir_translator.ml
TODO: Add support for loop specs
> [Rust] strlen using a loop

- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/mutex.rs
Also adds support for DerefMut.
This resolves two TODOs in mutex.rs (but adds a new one: verifying <MutexGuard<'b, T> as Deref>.deref).
> [Rust] Produce implicit outlives facts

- src/perf/perf.mli
- src/perf/perf.unix.ml
- src/perf/perf.win.ml
- src/perf/unix/perf_unix.ml
- src/perf/win/caml_perf.c
- src/perf/win/perf_win.ml
- src/rust_frontend/dune
- src/rust_frontend/rust_fe.ml
- src/win/SetErrorMode.ml
- src/win/caml_seterrormode.c
> [Rust] [Windows] Fix "Missing DLL" debugging

- bin/rust/std/lib.rsspec
- src/SExpressionEmitter.ml
- src/assertions.ml
- src/frontend/ast.ml
- src/frontend/ocaml_expr_of_ast.ml
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- src/verifast1.ml
- tests/errors/pred_confusion/pred_confusion.c
- tests/errors/pred_confusion/pred_confusion.h
- tests/rust/safe_abstraction/arc.rs
- tests/rust/safe_abstraction/arc_u32.rs
- tests/rust/safe_abstraction/rc.rs
- tests/rust/safe_abstraction/rc_u32.rs
- testsuite.mysh
- **Fix predicate confusion**
- **[Rust] Avoid predicate confusion in generated contracts & defs**
> Eliminate some sources of predicate confusion

- src/verifast1.ml
VeriFast now reports an error if a type predicate definition
for a struct type appears in a file that imports the struct
from another file, or if it contains two definitions of the
same type predicate for the same struct.
TODO: Check for duplicate type predicate definitions for
non-struct types.
> [Rust] Check for duplicate struct type pred defs

- src/cxx_frontend/ast_exporter/ExprSerializer.cpp
- src/cxx_frontend/ast_exporter/TypeSerializer.cpp
- src/cxx_frontend/expr_translator.ml
- src/cxx_frontend/stubs/stubs_ast.capnp
- src/cxx_frontend/type_translator.ml
- tests/cxx/arrays.cpp
- testsuite.mysh
This pull request adds support for array declaration and the array subscript operator ( operator[] ) in C++.
> [C++] Add array support

- src/verify_expr.ml
- tests/errors/issue589.c
- testsuite.mysh
> Deal gracefully with misplaced 'ensures'

- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/vfide/vfide.ml
Also: fix broken source location for lemma call in Rust.
> vfide: Ctrl+D shows definition in top window

- src/rust_frontend/vf_mir_translator/rust_parser.ml
- tests/rust/nonnull.rs
- tests/rust/safe_abstraction/cell_u32.rs
Also enables parsing nested expression call expressions like <T>.full_borrow_content(t, l)().
> [Rust] Open/close type predicates

- bin/rust/std/lib.rsspec
- src/SExpressionEmitter.ml
- src/frontend/ast.ml
- src/frontend/ocaml_expr_of_ast.ml
- src/frontend/parser.ml
- src/rust_frontend/vf_mir_exporter/src/preprocessor.rs
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/rust_frontend/vf_mir_translator/vf_mir_annot_parser.ml
- tests/rust/safe_abstraction/linked_list.rs
Also:
- Define <E>.own for enums E in .rsspec files
TODO:
- Define <E>.own for enums in .rs files
- Support box deref magic
> [Rust] Verified LinkedList::pop_front

- bin/rust/std/lib.rsspec
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/linked_list.rs
Only the S_mono lemmas expressing compliance with Rust
variance/subtyping have not yet been proven.
> [Rust] Prove most linked_list.rs proof obligations

- tests/rust/safe_abstraction/linked_list.rs
This brings the verified file closer to the original one.
> linked_list.rs: Uncomment the stability attributes

- rust_tutorials/purely_unsafe/solutions/account.rs
- rust_tutorials/purely_unsafe/solutions/byref.rs
- rust_tutorials/purely_unsafe/solutions/deposit.rs
- rust_tutorials/purely_unsafe/solutions/dispose.rs
- rust_tutorials/purely_unsafe/solutions/filter.rs
- rust_tutorials/purely_unsafe/solutions/fixpoints.rs
- rust_tutorials/purely_unsafe/solutions/foreach.rs
- rust_tutorials/purely_unsafe/solutions/lemma.rs
- rust_tutorials/purely_unsafe/solutions/limit.rs
- rust_tutorials/purely_unsafe/solutions/map.rs
- rust_tutorials/purely_unsafe/solutions/popn.rs
- rust_tutorials/purely_unsafe/solutions/pred.rs
- rust_tutorials/purely_unsafe/solutions/push_all.rs
- rust_tutorials/purely_unsafe/solutions/reverse.rs
- rust_tutorials/purely_unsafe/solutions/stack.rs
- rust_tutorials/purely_unsafe/solutions/sum.rs
- rust_tutorials/purely_unsafe/solutions/sum_full.rs
- rust_tutorials/purely_unsafe/solutions/values.rs
- rust_tutorials/purely_unsafe/solutions/verify.mysh
- src/mysh/mysh.ml
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- src/verifast1.ml
- src/verify_expr.ml
- tests/rust/testsuite.mysh
Also:
- In Rust, chunks are used for function pointers even if the
function type has no arguments.
- mysh now supports pushd and popd
> Started translating the tutorial solutions to Rust

- rust_tutorials/purely_unsafe/solutions/Makefile
- rust_tutorials/purely_unsafe/solutions/fractions0.rs
- rust_tutorials/purely_unsafe/solutions/verify.mysh
- src/frontend/ast.ml
- src/frontend/verifast0.ml
- src/rust_frontend/vf_mir_translator/rustbelt.ml
- src/verifast1.ml
Requires improved support for Rust function types.
> [Rust] Unsafe tutorial solution fractions0.rs

- .github/workflows/build.yml
Works around https://github.com/verifast/verifast/issues/612
> Windows build: Work around a dune bug

- bin/rust/list.rsspec
- bin/rust/listex.rsspec
- bin/rust/nat.rsspec
- bin/rust/prelude_core.rsspec
- bin/rust/prelude_core_core.rsspec
- bin/rust/std/lib.rsspec
- tests/rust/purely_unsafe/tree3.rs
- tests/rust/safe_abstraction/btree_node.rs
- tests/rust/safe_abstraction/rc.rs
- tests/rust/testsuite.mysh
Defined a predicate NodeRef.
Disclaimer: The predicate is completely untested for now;
I did not yet verify any code.
> btree_node.rs: first stab at meaning of NodeRef

- docs/rust-reference/src/non-unsafe-funcs.md
> VF4Rust Reference: clarify spec implication

- bin/rust/listex.rsspec
- bin/rust/std/lib.rsspec
- src/frontend/verifast0.ml
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- src/vfconsole/vfconsole.ml
- tests/rust/safe_abstraction/btree_node.rs
- tests/rust/testsuite.mysh
- **btree_node.rs: NodeType, pred Handle**
- **btree_node.rs: LeafNode::{init, new}**
> btree-node.rs: LeafNode::{init, new}

- tests/rust/safe_abstraction/ref_cell.rs
- tests/rust/testsuite.mysh
Proof added for a minimal version of RefCell that only supports mutable borrows.
> ref_cell.rs: Proof added

- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Add a proof of push_front_node to the refinement-checked version
of the linked_list.rs proof.
> linked_list.rs (refchecked): push_front_node

- setup-build.sh
Fixes failure in https://github.com/verifast/verifast/actions/runs/13629249564/job/38093188115
> Fix `brew install ./gtksourceview....gz` failure

- src/refinement_checker/main.ml
- src/refinement_checker/refinement_checker.ml
- tests/rust/refinement_checker/testsuite.mysh
- tests/rust/refinement_checker/wrapper_fns_verified.rs
- tests/rust/refinement_checker/wrapper_fns_verified2.rs
- tests/rust/refinement_checker/wrapper_fns_verified_bad.rs
- **refinement-checker: Eliminate List.nth calls**
- **refinement-checker: Refactor to support inlining**
- **refinement-checker: Inline wrapper calls**
- **refinement-checker: Substitute generic args**
> refinement-checker: Inline wrapper fns

- src/refinement_checker/main.ml
- src/refinement_checker/refinement_checker.ml
- src/rust_frontend/vf_mir/vf_mir.capnp
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/refinement_checker/option-map2_orig.rs
- tests/rust/refinement_checker/option-map2_verified.rs
- tests/rust/refinement_checker/option-map2_verified_bad.rs
- tests/rust/refinement_checker/option-map2_verified_bad2.rs
- tests/rust/refinement_checker/option-map2_verified_bad3.rs
- tests/rust/refinement_checker/option-map2_verified_bad4.rs
- tests/rust/refinement_checker/option-map_orig.rs
- tests/rust/refinement_checker/option-map_verified.rs
- tests/rust/refinement_checker/option-map_verified_bad.rs
- tests/rust/refinement_checker/testsuite.mysh
- **refinement-checker: Inline Option::map calls**
- **Update the MIR translator**
> refinement-checker: Inline Option::map calls

- bin/rust/std/lib.rsspec
> [Rust] init_ref_Box_in

- bin/list.c
- bin/list.gh
- examples/mcas/bitops_ex.vfmanifest
trivially, for L a list, if you replace L's i-th element by L's i-th element, the result is L
> Add a useful new lemma_auto in list.gh

- examples/relaxed/arc/arc.c
- examples/relaxed/relaxed.mysh
- **C source code for Arc**
- **Proof of ARC**
> Proof of ARC

- src/redux.ml
- tests/issue766.c
- testsuite.mysh
> Redux now looks for triggers inside E ? E : E

- src/refinement_checker/refinement_checker.ml
Introduces a Refinement Checker Intermediate Representation. Specifically, translates each MIR statement to a sequence of more fine-grained "commands" that operate on an operand stack. This enables a more fine-grained interleaving of evaluation and matching.
> [refinement-checker] Refactoring: RCIR

- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
They still need to have the same number of generic parameters, but the names can be different, at least for positive impls.
> [Rust] Send/Sync impl generics need not match ADT generics

- bin/rust/aliasing.rsspec
- src/refinement_checker/refinement_checker.ml
- src/refinement_checker/stringifier.ml
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Added the proof of fn pop_front_node to the refinement-checked version of the linked_list.rs proof.
> linked_list.rs: Refchecked pop_front_node

- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Added these functions to the refinement-checked version of the
proof.
> linked_list.rs: cursor_front_mut, cursor_back_mut

- tests/rust/safe_abstraction/linked_list.rs
TODO: Prove semantic well-typedness
> linked_list.rs: IterMut correctness

- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
> linked_list.rs: Refchecked(*) next and next_back

- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Verified and refinement-checked.
> linked_list.rs: iter_mut(), next(), next_back()

- bin/rust/std/lib.rsspec
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- src/verifast.ml
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Added a proof of split_off() to the refinement-checked
version of the linked_list.rs proof.
> linked_list.rs: Refchecked fn split_off()

- src/refinement_checker/refinement_checker.ml
- src/rust_frontend/vf_mir/vf_mir.capnp
- src/rust_frontend/vf_mir_exporter/src/lib.rs
- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
Added a proof of fn extract_if() to the refinement-checked version of the linked_list.rs proof.
> linked_list.rs: fn extract_if()

- bin/rust/prelude_core.rsspec
- tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs
Also adds some missing functional correctness postconditions.
> raw_vec.rs: pred RawVec: allocSize -> capacity

- src/rust_frontend/vf_mir_translator/rust_parser.ml
- tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs
Streamlined the creation of shared references
> raw_vec.rs: lem init_ref_RawVecInner

- bin/rust/prelude.rsspec
- bin/rust/rust_belt/lifetime_logic.rsspec
- bin/rust/rust_belt/points_to_at_lifetime.rsspec
- bin/rust/std/lib.rsspec
- src/rust_frontend/vf_mir_translator/rust_parser.ml
- tests/rust/safe_abstraction/btree_node.rs
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
- tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs
> [Rust] pred points_to_at_lft

- bin/rust/std/lib.rsspec
- tests/rust/safe_abstraction/arc.rs
- tests/rust/safe_abstraction/arc_u32.rs
- tests/rust/safe_abstraction/btree_node.rs
- tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
- tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs
- tests/rust/safe_abstraction/rc.rs
- tests/rust/safe_abstraction/rc_u32.rs
Also drops some more trailing underscores.
> Rename NonNull_ptr to NonNull::as_ptr

- src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
- tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs
The MIR translator computes, for each struct S defined by the program,
which type parameters of S are necessarily Send or Sync when S is Send.
For each of these, it used to add a separate precondition to the S_send
proof obligation. The problem with that is that the set computed by the
MIR translator is a conservative approximation, which does not take into
account the definitions of structs other than S. For example, this
analysis does not see that if RawVec<T, A> is Send, then A is
necessarily Send as well, because A only appears in the definition of
RawVec as part of type RawVecInner<A>, and the analysis does not look at
the definition of RawVecInner when analyzing struct S.
From now on, the precondition for S_send is simply is_Send(typeid(S)).
Separately, an is_Send_S_lemma autolemma …
> [Rust] Treat S_send PO pre semantically

- bin/prelude.h
> Remove unsound chars_to_boolean axiom
