verifast/verifast

bin/crt.vfmanifest
bin/prelude.h
src/parser.ml
src/verifast1.ml

Six predicates: `short_integer`, `u_short_integer`, `shorts`, `ushorts`, `malloc_block_shorts` and `malloc_block_ushorts`, two constants: `SHRT_MIN`, `SHRT_MAX`, necessary for basic support for pointers to standard C types: `short` and `unsigned short`.
Implemented by analogy to the `u_integer` and `uints` predicates.
Based on this discussion: https://groups.google.com/forum/#!topic/verifast/grGwdUnK4BU
And the issue: https://github.com/verifast/verifast/issues/42
P.S. the make target `testsuite` is very unstable on my laptop, I have to rerun it many times until it passes.

(unsigned) short pointer support. The predicates and supplimentary lemmas.

---

src/verifast1.ml

Allow unsigned char/short as a parameter to an inductive datatype. Testcase:
/ * @
inductive test1 = construct_test1(unsigned char);
inductive test2 = construct_test2(unsigned short);
@ * /
This fixes at least the internal errors of verifast during parsing of this testcase. I am not sure whether the patch will fail at some other place when we actually use the datatype.

Allow unsigned char/short in inductive data types

---

tutorial_solutions/fractions0.c

The solution to excercise 22 of the turorial was creating non-joinable threads while joinable threads were expected. The solution now correctly verifies using the latest version of verifast.

Fix a small error in one of the tutorial solutions.

---

src/linux/caml_stopwatch.c

Support non-Intel architecture, such like ARM which has no rdtsc.

Support non-Intel architecture

---

src/GNUmakefile

The ocamlfind package registered by z3 is named "Z3". On by linux machine, ocamlfind query z3 fails so Verifast's makefile needs to be changed to support Z3v4.5.

Capitalize the Z3 OcamlFind lib name

---

src/verifast.ml
src/vfconsole.ml

The help message suggests two values for the `-prover` option (redux and z3) but calling verifast with `-prover z3` fails when verifast is compiled with support for z3v4.5.
This commit adds a listing of supported provers both in the output of `verifast -help` and in the error message reported when a bad prover name is given to the `-prover` option.

List available provers in help and in the "No such prover" error message

---

bin/assoclist.gh

This fixes issue #89 where Z3 enters an infinite loop after a wrong guess of trigger.

[BUGFIX #89] Add a trigger to avoid a matching loop in Z3

---

src/vfide.ml

The `-disable_overflow_check` option for Vfide changes the default for the overflow checking option in the 'verify' menu; overflow checking can still be manually enabled from the menu.

Add option "-disable_overflow_check" to Vfide

---

src/GNUmakefile
src/combineprovers.ml
src/proverapi.ml
src/redux.ml
src/verifastPluginReduxZ3v4dot5.ml
src/z3prover.ml
src/z3v2prover.ml
src/z3v4dot5prover.ml
src/z3v4prover.ml

From two instances of the prover API, the function
`Combineprovers.combine` builds their product. This product also
follows the prover API.
Two combination modes are implemented:
- synchronised mode: both provers get all the queries,
- sequence mode: the second prover is only queried after the first
answers `unknown`.
A plugin for the combination of redux and z3 (v4.5) in sequence mode
is provided (-prover redux+z3v4.5).

Prover combination

---

src/.depend
src/GNUmakefile
src/smtlib.ml
src/smtlibprover.ml
src/verifastPluginCvc4.ml
src/verifastPluginExternalZ3.ml
src/verifastPluginReduxSmtlib.ml
src/verifastPluginZ3v4dot5Smtlib.ml

This adds support for the CVC4 SMT solver (option `-prover cvc4`)
using the SMTLib interface.

CVC4 as an external prover

---

src/parser.ml
tests/nodecl_and_semicolon.c
testsuite.mysh

In C language, following code is available:
```
$ cat main.c
/* No declarations */;
$ gcc -c main.c
$ echo $?
0
```

Parse semicolon without any declarations

---

src/lexer.ml
src/parser.ml

This patch includes some misc to verify FreeRTOS, which is located at following:
https://github.com/metasepi/amazon-freertos
But... On my laptop PC, verifying the `problem4.java` doesn't finish...
```
SLOW: examples/vstte2010$ verifast -prover z3v4.5 -c -disable_overflow_check problem4.java has been running for 645s
```

Fix misc to verify FreeRTOS

---

src/GNUmakefile

I couldn't compile verifast on Arch Linux using system packages because on Arch the num package is installed in `/usr/lib/ocaml/num` instead of `/usr/lib/ocaml`. With this change `ocamlfind` is used to locate the proper path for num.
~I also removed `nums.cmxa` from the vfide rules because it isn't needed.~

Use ocamlfind for ocaml-num

---

bin/rt/java.util.javaspec
examples/java/GenericClass.java
examples/java/frontend/big_example/Java7Program_desugared.java
src/SExpressionEmitter.ml
src/ast.ml
src/java_frontend/ast_translator.ml
src/parser.ml
src/verifast.ml
src/verifast1.ml
src/verify_expr.ml
tests/java/generics/QualifiedGenericMethodCall.java
testsuite.mysh

Added the possibility of creating methods that have local type arguments. These methods can only be called as a qualified call and if the type arguments are provided.
<Targ>call(); will not parse correctly
Utility.<Targ>call(); will verify correct
Utility.call(); will throw an error that insufficient type arguments are provided.

Qualified generic method call with explicit type arguments

---

examples/termination/ackermann.c
src/verifast.ml
src/verify_expr.ml

This patch adds support for recursive calls by rewriting the precondition of recursive calls as `[1]call_perm_(currentThread,foo) &*& (P)`.
It seems to work (and doesn't seem to allow arbitrary recursion), but I'm not entirely confident in this change. I'm especially suspicious of the scope parameters of `WVar`, but `LocalVar` and `FuncName` seem like they match?

Add termination checking support for direct recursion

---

bin/malloc.h

I ran into some difficulty using the existing `realloc` contract contract -- this change makes it simpler to use.
- The `newSize <= size` case is explicit. Using `take(newSize,cs)` is also fine if `newSize > size` -- `take(newSize,cs) == cs`.
- If `newSize > size`, the extra space is returned in a distinct `chars(...)`. This makes growing a buffer simpler -- if your heap looks like `malloc_block(buffer,cap) &*& buffer[..len] |-> cs &*& buffer[len+1..cap] |-> _`, then calling realloc when `len+1 == cap` no longer requires `chars_split` to get the heap back into shape.
- `realloc()` is now labelled as `terminates`.

Make the realloc contract nicer

---

src/verifast.ml
tests/issue206.c
testsuite.mysh

Fixes https://github.com/verifast/verifast/issues/206

Prioritize the old value of `x` over the current value of `old_x`.

---

bin/crt.vfmanifest
bin/prelude.h
examples/mcas/bitops_ex.vfmanifest
src/verifast1.ml

This is necessary and sufficient to make the following program verify:
```c
#include <stdbool.h>
#include <stdlib.h>
void x(bool* bs)
//@ requires bools(bs, ?c, ?lst);
//@ ensures bools(bs, c, lst);
{
//@ assert length(lst) == c;
}
int main(int argc, char** argv)
//@ requires true;
//@ ensures true;
{
bool* bs = malloc(10 * sizeof(bool));
if (bs == 0) return 1;
//@ assert malloc_block_bools(bs, 10);
//@ assert bools(bs, 10, ?bs_list);
//@ assert length(bs_list) == 10;
x(bs);
free(bs);
return 0;
}
```

Support sizeof(bool) and bools_inv

---

src/lexer.ml
src/parser.ml
tests/preprocessor_pragma/once_top.c
tests/preprocessor_pragma/once_top.h
tests/preprocessor_pragma/run.mysh
testsuite.mysh

This avoids the need to wrap each header in ifdef/define/endif.
I added support only at the beginning of a file; technically, `#pragma once` can appear anywhere in the file with the same effect (GCC and Clang both support this), but this is unlikely to happen in real code and I didn't see an obvious way to handle it in VeriFast's preprocessor, so I added an error in that case instead.

Add '#pragma once' support

---

src/GNUmakefile

This is a version of #158 that doesn't break the manual install case.
With this, the following script is enough to install everything needed to make VeriFast on Ubuntu 18.04, outsourcing the dependency-building part to opam:
```
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y -u ppa:avsm/ppa
sudo apt-get install -y --no-install-recommends \
ocaml opam \
g++ python2.7 m4 libgmp-dev `# for opam's z3` \
camlp4-extra `# for opam's camlp4` \
libgtk2.0-dev gtksourceview2.0-dev `# for opam's lablgtk`
opam init -y
eval $(opam config env)
opam install -y num z3.4.8.1 camlp4 conf-gtksourceview lablgtk
```

Makefile: Fix Z3_DLL_DIR when Z3 is installed using OPAM

---

src/verifast1.ml
tests/errors/shift_errors.c

6.5.7.3 of C99:
> The integer promotions are performed on each of the operands. The type of the result is
that of the promoted left operand. If the value of the right operand is negative or is
greater than or equal to the width of the promoted left operand, the behavior is undefined.
So we need to check the width regardless of the signedness of the type.

Check oversized left-shifts as well

---

examples/void_ignore.c
src/verifast1.ml
testsuite.mysh

These are used to suppress "unused parameter" compiler warnings.

Support void casts

---

examples/noreturn.c
src/parser.ml
testsuite.mysh

I added tests for the combinations of static and inline with _Noreturn while I was at it.

Support _Noreturn static functions

---

src/GNUmakefile
src/java_frontend/GNUmakefile
src/json.ml
src/json_tests.ml

Uses `ocamlfind ocamlopt` to compile and link. Following flags are passed to the compilation command:
- `-package <packages>`: additional search directories are included (`-I`) for the given list of packages. We don't have to provide those directories and `.cmxa` files explicitly anymore.
- `linkpkg`: packages listed via `-package` are linked in. Not required when you compile only (`-c`).

Compile using ocamlfind

---

examples/sizeof/packed.c
examples/sizeof/struct.c
examples/usbkbd/src/linux/input.h
examples/usbkbd/src/linux/usb.h
src/SExpressionEmitter.ml
src/ast.ml
src/explorer.ml
src/parser.ml
src/verifast1.ml
testsuite.mysh

I hope you're not getting tired of my pull requests 😬 
I have code that uses struct arrays and wanted to be able to reason about converting an array of chars to an array of structs, which requires knowing what size the structs are (or adding runtime checks, but that's annoying), and that can only be done if they're packed since otherwise the compiler is free to insert padding (and thus one cannot even reason about >1 struct since e.g. `2 * sizeof(struct xyz)` could overflow).
This PR does the following:
- Add an assumption that `sizeof` returns a value `<= SIZE_MAX`
- Add support for `__attribute__((packed))` (see `examples/sizeof/packed.c`)
- Fix the `usbkbd` example, as it was declaring members of types that were only defined later (which is illegal in C)
- Add an assumption that …

Improve sizeof handling, including packed structures

---

.gitignore
src/.depend
src/GNUmakefile
src/java_frontend/GNUmakefile
src/linux/GNUmakefile

Bytecode compilation allows visual debugging, e.g. in VS Code using earlybird.
This PR partially re-establishes bytecode compilation support in the Makefiles, without too many changes to the other stuff in there. Bytecode compilation is only supported for the core Verifast command line tool; and it has only been tested with a local OPAM switch and on macOS. The byte code target ("../bin/verifast.bc") is not included in the main targets (build; test; default).
The way things are set up, none of these changes should affect any other aspect of the build. But before doing anything else, let's first see whether the CI server agrees with this claim.
The disadvantage of this approach is that adding a module to verifast requires changes in multiple places of the Makefile.

Support for bytecode compilation?

---

src/cxx_frontend/cxx_ast_translator.ml
src/verifast.ml
src/verify_expr.ml
tests/cxx/c_copy/globals.cpp
tests/cxx/java_like/Account.h
tests/cxx/java_like/Stack.h
tests/cxx/java_like/account_client.cpp
tests/cxx/java_like/stack_client.cpp
testsuite.mysh

- Constructor contract is checked when an object is allocated on the stack
- Destructor contract is checked when an object is deallocated on the stack (or goes out of scope)

Stack (de)allocation

---

bin/stdint.h
src/SExpressionEmitter.ml
src/cxx_frontend/ast_exporter/Annotation.cpp
src/cxx_frontend/ast_exporter/Annotation.h
src/cxx_frontend/ast_exporter/AnnotationStore.h
src/cxx_frontend/ast_exporter/AstSerializer.cpp
src/cxx_frontend/ast_exporter/AstSerializer.h
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.cpp
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.h
src/cxx_frontend/ast_exporter/DeclSerializer.cpp
src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/ast_exporter/FixedWidthInt.h
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/ast_exporter/TypeSerializer.cpp
src/cxx_frontend/ast_exporter/VerifastASTExporter.cpp
src/cxx_frontend/ast_exporter/loc_serializer.h
src/cxx_frontend/cxx_ast_translator.ml
src/cxx_frontend/stubs/stubs_ast.capnp
tests/cxx/c_copy/truncating.cpp
testsuite.mysh

- Support for truncating expressions (`/*@ truncating @*/`)
- Support for fixed-width integer types (`int8_t`, `uint_8t`,...) declared in `bin/stdint.h`
- Better support for source information of types. Previously, no source information was kept for *inner* types. E.g., `int` in `int *`. Now there are two separate visitors for `Type`s and `TypeLoc`s. The difference is that `TypeLoc` refers to a type that was written in the source code. `Type` can refer to any (implicit) type, like the type of `this` in a class. When serializing a `TypeLoc`, all source information is kept, also for *inner* types. Previously, the serialization of `TypeLoc`s was simply delegated to the `TypeVisitor`, which dropped source information of inner types. This change is mainly responsible for the changes in many …

Truncating expressions and fixed-width integer types

---

examples/preprocessor/bad_gh_include.c
examples/preprocessor/bad_include.gh
examples/preprocessor/multiple_gh_include.c
examples/preprocessor/preprocessor.mysh
src/parser.ml

The parser rejects following ghost snippets **while translating** header includes:
- ```c
/*@
#include "bar.gh"
#include "foo.gh"
@*/
```
The closing annotation symbol is required after the first `#include`.
- ```c
/*@
#define BAR 1
@*/
//@ #include "bar.gh"
```
Other preprocessor directives cannot be used without using an `#include` directive in the same block of ghost code.
- ```c
/*@
@*/
//@ #include "bar.gh"
```
An `#include` directive is expected in the empty block of ghost code.
This PR enhances the parser to be able to parse these snippets.

Allow multiple preprocessor directives in the same block of ghost code

---

bin/prelude.h

To the string_to_chars lemma in the post condition, added the assertion of the string having a null terminator at the end. This will satisfy the precondition of the null terminator check for chars_to_string. This addition helps when doing a string_to_chars to something and then later having a chars_to_string to convert it back.

Check for null terminator in lemma string_to_chars

---

src/verifast.ml
src/verifast0.ml
src/verifast1.ml
src/verify_expr.ml
tests/cxx/inheritance/diamond.cpp
tests/cxx/inheritance/multiple_inheritance.cpp
tests/cxx/inheritance/single_inheritance.cpp

[C++ draft n4910](https://github.com/cplusplus/draft/releases/tag/n4910) §11.9.3 - Initializing bases and members [class.base.init]/16:
> Member functions (including virtual member functions, 11.7.3) can be called for an object under construction. (...) However, if these operations are performed in a ctor-initializer (or in a function called directly or indirectly from a ctor-initializer) before all the mem-initializers for base classes have completed, the program has undefined behavior.

Verify that all bases are constructed when a method is called

---

src/cxx_frontend/ast_exporter/Annotation.cpp
src/cxx_frontend/ast_exporter/Annotation.h
src/cxx_frontend/ast_exporter/AnnotationStore.h
src/cxx_frontend/ast_exporter/AstSerializer.cpp
src/cxx_frontend/ast_exporter/AstSerializer.h
src/cxx_frontend/ast_exporter/CommentProcessor.cpp
src/cxx_frontend/ast_exporter/CommentProcessor.h
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.cpp
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.h
src/cxx_frontend/ast_exporter/DeclSerializer.cpp
src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/ast_exporter/FixedWidthInt.h
src/cxx_frontend/ast_exporter/FunctionMangler.h
src/cxx_frontend/ast_exporter/Inclusion.h
src/cxx_frontend/ast_exporter/InclusionContext.cpp
src/cxx_frontend/ast_exporter/InclusionContext.h
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/ast_exporter/StmtSerializer.cpp
src/cxx_frontend/ast_exporter/TypeSerializer.cpp
src/cxx_frontend/ast_exporter/VerifastASTExporter.cpp
src/cxx_frontend/cxx_annotation_parser.ml
src/cxx_frontend/cxx_ast_translator.ml
src/cxx_frontend/cxx_fe_sig.ml
src/cxx_frontend/stubs/stubs_ast.capnp

Some refactoring of the C++ frontend in preparation for instance predicates. The C++ code refactoring mainly changes member variables from `_member` to `m_member`.

[C++] Refactor frontend

---

bin/arrays.c
bin/arrays.gh
bin/crt.vfmanifest
bin/malloc.h
bin/prelude.h
examples/crypto_ccs/crypto_ccs/crypto/crypto_chars.gh
examples/crypto_ccs/crypto_ccs/crypto/cryptogram.c
examples/crypto_ccs/crypto_ccs/crypto/cryptogram.gh
examples/crypto_ccs/symbolic_model/src/general.c
examples/crypto_ccs/symbolic_model/src/general.h
examples/crypto_ccs/symbolic_model/src/item.h
examples/crypto_ccs/symbolic_model/src/item_tags.c
examples/custom_bindir/bin/stdlib/prelude.h
examples/mcas/bitops_ex.vfmanifest
examples/mcas/mcas.c
examples/mcas/mcas_client.c
examples/mcas/rdcss.c
examples/tso/cvm0.c
examples/vstte2012/problem3/problem3.c
examples/vstte2012/problem3/problem3_alt.c
src/verifast1.ml
src/verify_expr.ml

So far, the only check VeriFast did on pointer arithmetic is that the address did not exceed the limits of uintptr_t.  With this breaking change, VeriFast checks that the result of pointer arithmetic is within the limits associated with the pointer's provenance. The limits of the null pointer provenance coincide with those of uintptr_t; the limits of other provenances are unspecified except that the minimum address is greater than zero, the maximum address is at most UINTPTR_MAX, and if an object is allocated at a given provenance, the addresses of that object's representation bytes, as well as the one-past address, are within the provenance's limits.
A very useful consequence is that the only pointer whose address is zero is the null pointer.
To port your code, it should suffice to …

Impose tight limits on pointer arithmetic

---

bin/crt.vfmanifest
bin/prelude.h
examples/MockKernel/MockKernel.c
examples/crypto_ccs/symbolic_model/src/network.c
examples/jayanti/jayanti.c
examples/mcas/bitops_ex.vfmanifest
examples/mcas/mcas_client.c
examples/queue/queue.c
examples/queue/queue.h
examples/queue/queue_client.c
examples/shared_boxes/atomic_integer.h
examples/shared_boxes/cell_refcounted.c
examples/shared_boxes/concurrentqueue.c
examples/shared_boxes/cowl.c
examples/shared_boxes/lcl_set.c
examples/splitcounter/splitcounter.c
examples/tso/cvm0.c
examples/usbkbd/src/linux/input.h
examples/usbkbd/src/linux/spinlock.h
examples/usbkbd/src/linux/usb/ch9.h
examples/usbkbd/src/usbkbd_verified.c
examples/usbkbd/src/usbmouse.c
soundness.md
src/assertions.ml
src/verifast1.ml
tests/pointer_limits.c
testsuite.mysh

Also checks them when taking the address of an array element. This breaking change fixes a long-standing unsoundness.
This change should only cause proof breakage in cases where you are taking the address of a field for which the thread does not currently own a field chunk, *and* where the field is not the first field of the struct.

Check pointer limits when taking a field's address

---

src/verifast.ml
tests/cxx/inheritance/method_call_in_dtor.cpp
testsuite.mysh

`X_bases_constructed` was consumed too early when verifying a destructor, which didn't allow to call methods during destruction.

[C++] Consume bases_constructed at end of destructor body

---

.github/workflows/build.yml
appveyor.yml
setup-windows.bat

Build and test cases succeed with vfdeps built on Cygwin x86

Cygwin x86_64

---

bin/prelude.h
tests/alloc_zero.c
testsuite.mysh

I couldn't figure out how to prove:
```
lemma void integers__limits(void *array);
requires [?f]integers_(array, ?sz, ?sgn, ?n, ?cs) &*& n > 0;
ensures [f]integers_(array, sz, sgn, n, cs) &*& (void *)0 <= array
&*& array + n <= (void *)UINTPTR_MAX
&*& array + n*sz <= (void *)UINTPTR_MAX;
```
because there didn't seem to be any axiom guaranteeing `sz >= 1`. This seems like a reasonable spot to add that axiom.

Forbid negative-size objects

---

.github/workflows/build.yml
.gitignore
config.sh
setup-build.sh
setup-windows.bat
setup-windows.sh
src/GNUmakefile
src/cxx_frontend/Makefile
src/cxx_frontend/ast_exporter/AstSerializer.cpp
src/cxx_frontend/ast_exporter/CMakeLists.txt
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.cpp
src/cxx_frontend/ast_exporter/ContextFreePPCallbacks.h
src/cxx_frontend/ast_exporter/DeclSerializer.cpp
src/cxx_frontend/ast_exporter/FixedWidthInt.h
src/cxx_frontend/ast_exporter/InclusionContext.h
src/cxx_frontend/ast_exporter/LocUtil.cpp
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/cxx_annotation_parser.ml
src/explorer.ml
src/java_frontend/ast_reader.ml
src/java_frontend/ast_translator.ml
src/lexer.ml
src/linemarks/Makefile
src/linux/caml_stopwatch.c
src/parser.ml
src/smtlib.ml
src/verifast1.ml
src/vfide.ml
src/win/caml_stopwatch.c

Updated to use new vfdeps and new parser syntax. (`depend` target is a lot faster now because we don't have to preprocess it with `camlp4`)

Use new vfdeps

---

src/redux.ml
tests/cxx/virtual_methods/multiple_inheritance.cpp

Simplify nested `field_ptr_parent(field_ptr(target, _, offset), offset)` to `target` in redux.

Simplify pointers in redux

---

src/assertions.ml

The comment for a *path* in an *edge* was outdated due to changes introduced in #368.

Update path comment for auto open/close

---

setup-windows.sh

Standard users cannot create files in `C:\`.

setup-windows.sh: download into C:\verifast-downloads

---

src/rust_frontend/vf_mir_exporter/capnproto-rust/benchmark/carsales.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/benchmark/catrank.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp-rpc/examples/calculator/server.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp-rpc/src/rpc.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp/src/list_list.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp/src/primitive_list.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp/src/schema.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp/src/struct_list.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnp/src/traits.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnpc/src/codegen.rs
src/rust_frontend/vf_mir_exporter/capnproto-rust/capnpc/src/codegen_types.rs
src/rust_frontend/vf_mir_exporter/src/lib.rs

- Take usize lengths and indices instead of u32
- Add `fill` method

[Rust] Simplify building capnp struct lists

---

src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/drop_test.rs
tests/rust/testsuite.mysh

TODO: Support implementing Drop for Tree in tree.rs. This requires
drop elaboration for verifying function new_nonempty.

[Rust] Support implementing the Drop trait

---

src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/safe_abstraction/tree.rs

Does not actually support implicit drops yet; for now,
only code where implicit drops do not actually happen
is supported.
VeriFast now consumes drop-elaborated MIR, so that
drop terminators are run only on locals whose
content has not been moved out.

[Rust] Support locals that impl Drop; ManuallyDrop

---

.github/workflows/build.yml
src/cxx_frontend/ast_exporter/AstSerializer.h
src/cxx_frontend/ast_exporter/Concept.h
src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/ast_exporter/StmtSerializer.cpp

Concepts require g++ >= 10, which is not available by default on Ubuntu 20.04

[C++] Exporter: do not use concepts if unsupported

---

src/SExpressionEmitter.ml
src/assertions.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/verifast1.ml

It is subsumed by PureFuncName (which was added later).

Refactoring: Eliminate redundant PureCtor scope

---

src/cxx_frontend/decl_translator.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
tests/rust/safe_abstraction/cell_u32.ml
tests/rust/testsuite.mysh

Also: typedefs now take type parameters, but this is not (yet)
very useful for C programs since ghost typedefs are not yet
supported.
TODO: Support generic structs in safe function signatures.

[Rust] Generic structs

---

bin/prelude.h
bin/prelude_rust_core.gh
src/assertions.ml
src/frontend/verifast0.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
src/verify_expr.ml
tests/rust/purely_unsafe/deque_i32.rs
tests/rust/testsuite.mysh

Includes the following minor improvements:
- Uninitialized generic points-to chunks
- Chunk consumption is logged at -verbose N with N >= 4
- [Rust] Generic impls
- [Rust] Parser parses `Foo<Bar<T>>` as `Foo< Bar<T> >`
- [Rust] Generic pred/lem declarations
- [Rust] ptr::read/write()
- [Rust] Real type parameters must be uppercase and carry a typeid
- Inference of type parameters under pointers and in struct type args
- Typeid env is available in more consumption contexts

[Rust] Generic purely unsafe deque.rs

---

bin/rust/rust_belt/general.h
src/rust_frontend/vf_mir_translator/rustbelt.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
tests/rust/safe_abstraction/tparam_own.rs
tests/rust/testsuite.mysh

This commit enables expressing ownership of values of type T where
T is a type parameter. This is accomplished by adding a T_own
parameter to each function with a type parameter T. When calling
such a function, the `own` predicate for the type argument is
passed in. Since struct own predicates take each field as a
separate argument, an S_own_ predicate that takes a struct value
is generated automatically for each struct S, expressed in terms
of the user-defined S_own predicate. S_own_ is passed when calling
functions with struct S as a type argument.
This commit also builds ghost commands
open_full_borrow_content::<T>(t, l)
and
close_full_borrow_content::<T>(t, l)
into the VeriFast engine. These consume/produce
T_full_borrow_content(t, l)()
and produce/consume
generic_points_to<T>(l, ?v) …

[Rust] T_own for tparams; open/close_fbc::<T>

---

bin/rust/rust_belt/general.h
src/rust_frontend/vf_mir_translator/rustbelt.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/shared_primitive_types.rs
tests/rust/safe_abstraction/tparam_own.rs
tests/rust/testsuite.mysh

- **Reformat vf_mir_translator.ml (addendum to 906236de86ec1ad26da8efa7318bc694d3d5e1f3)**
- **Refactoring: make own_pred and fbc into exprs**
- **[Rust] shr_pred and other shared refs work**
- **[Rust] Pass T_share arg for each generic param T**

[Rust] Pass T_share arg for each generic param T

---

examples/generic_pred_ctors.c
src/assertions.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/verifast1.ml
src/verify_expr.ml

Expressions of the form (E)(args) in assertion position are now
interpreted as assertions. E must be of predicate type.

Predicate expression assertions

---

bin/rust/rust_belt/general.h
src/assertions.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
src/verify_expr.ml
tests/rust/safe_abstraction/tparam_own.rs
tests/rust/safe_abstraction/tree.rs

fbc, share off the typeid,Specifically, this commit introduces a "type predicates" construct into the VeriFast engine. This enables associating predicates with types, such that they can be retrieved using `<T>.own`/`<T>.share` syntax.
Note: this approach means distinct Rust types (with distinct RustBelt
type interpretations) must be mapped to distinct VF types.
TODO: Introduce a separate VF type for Rust type `char`.

[Rust] Hang own, fbc, share off the typeid

---

tests/cxx/virtual_methods/multiple_inheritance.cpp

Moves virtual method calls from destructor to constructor.

[C++] Fix multiple inheritance test

---

bin/rust/std/lib.rsspec
src/rust_frontend/vf_mir_translator/rust_parser.ml
tests/rust/purely_unsafe/httpd.rs
tests/rust/purely_unsafe/httpd_mt.rs

Extends the .rsspec file parser with support for
- Enums
- Generic impl blocks
- Type alias declarations
- Trait declarations
- Ref types
- Tuple types
Adds specs for the following std items:
- fn std::mem::Drop
- enum std::result::Result
- fn std::result::Result::unwrap
- struct std::io::Error
- type std::io::Result
- trait std::io::Write with required fns write and flush
- struct std::io::Stdout
- fn std::io::stdout

[Rust] Writing to stdout

---

src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/parser_test.rs
tests/rust/purely_unsafe/httpd.rs
tests/rust/purely_unsafe/httpd_mt.rs
tests/rust/safe_abstraction/mutex_u32.rs

If the user declares neither S_own nor S_share, one can imagine S_own
and S_share as being defined as `false`; for those definitions, the
proof obligations hold trivially.

[Rust] Generate POs for S iff S_own or S_share declared

---

src/cxx_frontend/ast_exporter/Concept.h
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/ast_exporter/StmtSerializer.cpp
src/cxx_frontend/stmt_translator.ml
src/cxx_frontend/stubs/stubs_ast.capnp
tests/cxx/loops.cpp
testsuite.mysh

Adds support for 'for' loops and 'continue' statements for C++ and solves issue #475 for C++ (instead of C).

[C++] Support for 'for' loops and 'continue' statements

---

src/cxx_frontend/ast_exporter/CMakeLists.txt

Highest version on Ubuntu 20.04 is 3.16. The action runner has >3.20 preinstalled in its image.

Revert cmake required minimum version

---

src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/expr_translator.ml
src/cxx_frontend/stubs/stubs_ast.capnp
src/verifast1.ml
tests/cxx/casts.cpp
testsuite.mysh

For clang, uintptr_t is just a typedef that may be defined by the programmer itself. To support calculations with pointer values anyway I added support for casts from pointers to integer types. The Verifast core supported this for integers with PtrRank only so far. So I had to add support for those casts more generally.
Please have a closer look at my added line in verifast1.ml to be sure that my changes are sound.
The removed line in verifast1.ml had an exact duplicate some lines below.

[C++] Support Pointer to Integer casts

---

src/cxx_frontend/ast_exporter/AstSerializer.cpp
src/cxx_frontend/ast_exporter/AstSerializer.h
src/cxx_frontend/ast_exporter/DeclSerializer.cpp
src/cxx_frontend/ast_exporter/Location.cpp
src/cxx_frontend/ast_exporter/Location.h
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/ast_exporter/StmtSerializer.cpp
src/cxx_frontend/ast_exporter/VerifastASTExporter.cpp

This commit adds a generic `NodeListSerializer` class to support serialization for lists of nodes for which the length is not known in advance.
It does so by providing an API to iteratively serialize nodes. Internally, it serializes the actual nodes to *orphans*. These orphans can later adopted to an appropriate builder.

[C++] `NodeListSerializer`: list serialization

---

src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/frontend/ast.ml
src/frontend/parser.ml
src/verifast1.ml
src/vfconsole/vfconsole.ml
src/vfide/vfide.ml
tests/cxx/casts.cpp
testsuite.mysh

This pull request contains the following changes:
- Support for integer down-cast in C++ (using C-Style-Casts)
- Enables verification of .hpp files
- Fixes error when including C++ standard library headers (e.g. "#include &lt;cstdint&gt;") caused by requirement for file extension
- Fixed error of dummy locations in clang error messages.
- Removed deprecated target specification for casts.cpp test case.

[C++] Collection of small changes

---

src/cxx_frontend/ast_exporter/Error.h
src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/ast_exporter/NodeSerializer.h
src/cxx_frontend/expr_translator.ml
src/cxx_frontend/stubs/stubs_ast.capnp
tests/cxx/operators.cpp

This pull request adds support for the conditional operator ('?'-operator) in C++.
It also fixes a bug in Error.h that caused a segmentation violations in case of an invalid location while calling fullLoc.getFileEntry().

[C++] Add support for conditional operator

---

examples/futexes/atomics.h
examples/futexes/futex.h
examples/futexes/mutex.c

Fixes the unsoundness that results if multiple futexes, with
different values for `dequeuePost` or `callPermFunc`, are active
at the same time at the same address. In particular,
the spec of futex_wake_one is sound only if the thread being
awoken produces the same dequeuePost resource expected by the
awaking thread.

futex.h: disallow multiple futexes at same word

---

src/cxx_frontend/ast_exporter/AnnotationManager.cpp
src/cxx_frontend/ast_exporter/DeclSerializer.cpp
src/cxx_frontend/ast_exporter/NodeListSerializer.h
src/cxx_frontend/decl_translator.ml
src/cxx_frontend/stubs/stubs_ast.capnp
tests/cxx/new_class.cpp
tests/cxx/virtual_methods/virtual_methods.cpp

Till now deleted and defaulted functions caused segmentation violations during serialization because they are definitions but don't have a body. This pull request should make the serializer ignore deleted functions and create error messages for defaulted functions.
Deleted functions must not be used by the programmer and clang should already check that this is ensured. This should imply that we don't need to pass them to verifast and thus don't need to serialize them at all.
Defaulted functions are more complicated. I added an error message for them to replace the segmentation violations by hopefully expressive output.
@NielsMommen I think the most important part to look at is the change in NodeSerializer.h. Maybe you have an idea how to do better.

[C++] Deleted and Defaulted functions

---

src/verify_expr.ml
tests/cxx/declarations.cpp
testsuite.mysh

I need to write header files to get support for some UNIX standard functions and there inside I used function declarations that have parameters without a name. This caused the error message "Duplicate parameter name" for those with multiple unnamed parameters. To avoid others to run into the same problem, I wrote this change request. I hope my change in _verify_expr.ml_ is the right way to solve the problem.

Allow unnamed function parameters

---

bin/permutations.c
bin/permutations.gh

Hi,
I wanted to use `is_permutation_reflexive` in `bin` but realized that it's not for general types so I got errors. Hence, I made changes to use `is_permutation_reflexive` for all types.

Update `is_permutation_reflexive` for general types

---

bin/rust/std/lib.rsspec
src/frontend/util.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_exporter/src/preprocessor.rs
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
src/vfconsole/vfconsole.ml
tests/rust/purely_unsafe/atomics_example.rs
tests/rust/purely_unsafe/my_option.rs
tests/rust/testsuite.mysh

This commit:
- Starts spec'ing out AtomicUsize
- Adds an example that uses AtomicUsize
- Adds support for verifying programs that refer to variants of
enums declared in extern crates (including std).
This involved updates to how the exporter exports aggregates
and changes in how enum variants are translated.
- Fixes a bug in the treatment of blocks with ghost declarations
in the Rust preprocessor.
- Disables the strict aliasing checks when verifying Rust programs.
- Adds options -dump_asts and -dump_asts_with_locs to the
'verifast' command-line tool

[Rust] atomics_example.rs

---

src/redux.ml
tests/issue536.c
testsuite.mysh

When evaluating x << N where N is a literal between 0 and 64,
VeriFast produces the fact that x << N == x * 2^N. It now does
so only when the expression occurs outside the body of a fixpoint
function.
Fixes #536

Produce shift left fact only outside fixpoint

---

bin/prelude.h

Was inconsistent with -assume_no_provenance which assumes
that all provenances are equal.

Fix unsoundness in field_ptr_provenance_injective

---

bin/crt.vfmanifest
bin/prelude.h
examples/mcas/bitops_ex.vfmanifest
src/assertions.ml
src/verifast1.ml
src/verify_expr.ml
tests/effective_types.c
tests/integer__pointee_pred.c
tests/issue504.c
testsuite.mysh

Also, *p |-> PAT and p[PAT1..PAT2] |-> PAT3 assertions where
p is of type (u)intN_t* now assert has_type(p, &typeid((u)intN_t)) == true.
This breaking change fixes #504, an unsoundness. You can disable
effective types checks by specifying the -fno-strict-aliasing
command-line flag.

Enforce effective types for (u)intN_t accesses

---

examples/close_struct_zero.c
src/verifast.ml
src/verify_expr.ml
tests/effective_types.c
testsuite.mysh

This breaking change fixes #540, an unsoundness. You can disable
this check by specifying the -fno-strict-aliasing flag.

close_struct: Check effective type

---

bin/prelude_rust_core.gh
bin/rust/std/lib.rsspec
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
tests/rust/purely_unsafe/account.rs
tests/rust/purely_unsafe/deque.rs
tests/rust/purely_unsafe/deque_i32.rs
tests/rust/purely_unsafe/httpd.rs
tests/rust/purely_unsafe/httpd_mt.rs
tests/rust/purely_unsafe/reverse.rs
tests/rust/purely_unsafe/tree.rs
tests/rust/purely_unsafe/tree2.rs
tests/rust/purely_unsafe/tree3.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/deque_i32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/safe_abstraction/tree.rs

The spec now takes alignment into account.
Also:
- Remove special-casing of type Layout
- Add support for fixpoints with type parameters that carry a typeid.
- In Rust, try to interpret compound paths as relative to the current module, if interpreting as absolute fails.

[Rust] Fix unsound treatment of alloc/dealloc

---

bin/rust/std/lib.rsspec
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
tests/rust/purely_unsafe/account_with_box.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
tests/rust/testsuite.mysh

Box can now be used instead of alloc/dealloc in certain cases.
Also:
- Add open_generic_points_to and close_generic_points_to ghost commands
- Define <S>.own and <S>.share for structs S for which custom S_own or S_share predicates are defined and that have no type parameters or lifetime parameters. Additionally, if the fields of such a struct are not trivially droppable and it does not implement the Drop trait, an S_drop proof obligation is now generated to enforce that ownership of S implies ownership of its fields.

[Rust] Start adding spec for Box

---

bin/rust/prelude.rsspec
bin/rust/prelude_core.rsspec
bin/rust/std/lib.rsspec
src/assertions.ml
src/verifast.ml
src/verifast1.ml
src/verify_expr.ml
tests/rust/nonnull.rs
tests/rust/purely_unsafe/account_with_box.rs
tests/rust/purely_unsafe/alloc.rs
tests/rust/purely_unsafe/atomics_example.rs
tests/rust/purely_unsafe/httpd.rs
tests/rust/purely_unsafe/httpd_mt.rs
tests/rust/purely_unsafe/httpd_vec.rs
tests/rust/purely_unsafe/reverse.rs
tests/rust/purely_unsafe/str.rs
tests/rust/purely_unsafe/strlen.rs
tests/rust/purely_unsafe/tree2.rs
tests/rust/purely_unsafe/tree3.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/unverified/platform/spec/lib.rsspec

This commit decommissions the type-specific points-to predicates
(integer_, pointer, etc.)
in favor of generic_points_to, which it renames to just points_to.
Similarly, the type-specific array predicates (integers_ etc.)
are decommissioned in favor of the generic 'array' predicate.

[Rust] Use 'points_to<T>' and 'array<T>' only

---

bin/prelude.h
examples/BeepDriver/BeepKernel.c
examples/MockKernel/AdderModule.c
examples/abstract_io/chat_server/queues.c
examples/chat.mysh
examples/crypto_ccs/symbolic_model/protocols/recursive_otway_rees/recursive_otway_rees.c
examples/crypto_ccs/symbolic_model/protocols/recursive_otway_rees/recursive_otway_rees.h
examples/globals.c
examples/helloproc/helloproc_main.c
examples/insertion_sort.c
examples/io/matching_brackets/matching_brackets_checker.c
examples/queue/queue.c
examples/queue/queue.h
examples/vstte2012/problem4/treerec.c
examples/vstte2012/problem4/treerec_tree.c
examples/vstte2012/problem4/treerec_tree.h
src/assertions.ml
src/frontend/ast.ml
src/verifast1.ml
src/verify_expr.ml
tests/cxx/c_copy/globals.cpp
tutorial_solutions/byref.c
tutorial_solutions/students.c

This breaking change causes VeriFast to check effective types
when accessing a variable of type T*. Fixes #542, an unsoundness.
You can disable the effective types checks by specifying the
-fno-strict-aliasing command-line option.

Check effective types for pointer-typed accesses

---

src/rust_frontend/rust_fe.ml

vf-rust-mir-exporter is now started with LD_LIBRARY_PATH pointing
to $(rustc +nightly-2023-12-31 --print sysroot)/lib instead of
$(rustc +nightly-2023-12-31 --print target-libdir).
This fixes #560.

[Rust] Look for DLLs in $sysroot/lib

---

src/assertions.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/rustbelt.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/nonnull.rs
tests/rust/purely_unsafe/account_with_box.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/deque_i32.rs
tests/rust/safe_abstraction/drop_test.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/safe_abstraction/tree.rs

For a struct S, the S_own predicate now takes a thread_id_t and an S value, instead of a thread_id_t and a value for each field of S.
This is in preparation for retiring _own predicates in favor of <T>.own. It also eliminates the difference between the treatment of structs whose body is known and those whose body is not known.
Also improves support for dereferencing struct pointers.

[Rust] _own takes struct value, not field values

---

src/assertions.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/nonnull.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/unverified/sys/spec/lib.rsspec

This requires that S_own and S_share be predicate constructors, because it must be possible to pre-apply the type arguments.
VeriFast now also generates an S_drop proof obligation for generic structs S that are not trivially droppable and that do not implement the Drop trait.

[Rust] Define <S>.own and <S>.share for generic structs S

---

bin/rust/rust_belt/general.rsspec
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/rustbelt.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
tests/rust/nonnull.rs
tests/rust/purely_unsafe/account_with_box.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/deque_i32.rs
tests/rust/safe_abstraction/drop_test.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/mutex_u32_with_lft_param.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/safe_abstraction/tree.rs

Adds support for
pred<T> <S<T>>.own(t, v) = ...;
syntax. This is shorthand for
pred S_own<T>(t, v) = ...;
type_pred_def<T> <S<T>>.own = S_own;
The Rust translator no longer generates type predicate definitions for .own and .share; if the user wants them, they have to use this new syntax.
Adapted the examples to use the new syntax, which will become mandatory in a future commit.
Also refactored the Rust translator: removed the .own_pred and .shr_pred fields of the ty_interp struct, which were no longer being used.

[Rust] Inline type predicate definitions

---

src/cxx_frontend/ast_exporter/ExprSerializer.cpp
src/cxx_frontend/decl_translator.ml
tests/cxx/declarations.cpp
testsuite.mysh

Adds support for default values of function parameters by handling them as if they were passed explicitly.

[C++] Added support for default values of function parameters

---

src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/duplicate_type_pred_defs.rs
tests/rust/public_fields.rs
tests/rust/testsuite.mysh
tests/rust/type_pred_defs_for_imported_structs.rs

Allowing public fields is unsound unless we generate additional proof obligations.

[Rust] Forbid public fields for now

---

src/frontend/ast.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs

For each struct S defined in the crate being verified:
- VeriFast determines whether the struct is Send/Sync:
- It computes whether the struct automatically implements Send or Sync. This is the case if each field's type is Send/Sync. Currently, VeriFast computes a very rough approximation of whether a field type is Send/Sync. Apart from a few special cases (raw pointers, NonNull, UnsafeCell, type parameters) for the purposes of this computation it considers each type to implement Send and Sync. If the struct is generic, VeriFast computes an approximation of the trait bounds on the type parameters under which the struct is Send/Sync. (Specifically, for Send, it only records Send bounds, and for Sync, it only records Sync bounds.)
- It takes into account negative and positive impl items.
- …

[Rust] Generate Send/Sync proof obligations

---

src/dune
src/frontend/ast.ml
src/frontend/stats.ml
src/rust_frontend/rust_fe.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/verifast1.ml
src/vfconsole/vfconsole.ml
src/vfide/vfide.ml
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs

Since VeriFast uses rustc, which always assumes a specific target triple, a VeriFast run is sound only for that target triple. From now on, VeriFast mentions the target triple in the success message.
Also, a default C target (aka data model) is now assumed if none is specified: LLP64 on Windows and LP64 on Linux and MacOS. The data model is also mentioned in the success message.
This resolves some TODOs in the examples.
Fixes #579

[Rust] Always run in targeted mode

---

src/frontend/dune
src/frontend/verifast0.ml
src/json/json.ml
src/rust_frontend/dune
src/rust_frontend/rust_fe.ml
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/vfconsole/vfconsole.ml
src/vfide/dune
src/vfide/vfide.ml

If rustc aborts because of compilation errors, show the first error just like a regular VeriFast verification failure.

[Rust] Improve UX on rustc errors

---

tests/rust/README.md
tests/rust/purely_unsafe/README.md
tests/rust/purely_unsafe/httpd.rs
tests/rust/purely_unsafe/httpd_mt.rs
tests/rust/purely_unsafe/httpd_vec.rs
tests/rust/purely_unsafe/mt_account_transfer.rs

The verifast_options make it so that the program verifies
in vfide without having to provide any command-line arguments or
change any settings in the menu.

[Rust] Add README; add missing verifast_options

---

bin/rust/std/lib.rsspec
src/assertions.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs

Also:
- Improve source locations for generated contracts
- Support type predicate definitions in modules
- Allow fixpoints that return predicates where predicate constructors are expected when typechecking, producing, and consuming assertions
TODO: Define S_shared, <S>.shared for structs S in .rsspec files

[Rust] Define S_own, <S>.own, S_fbc, <S>.fbc for structs S in .rsspec files

---

src/frontend/ast.ml
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/rustbelt.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/nonnull.rs
tests/rust/safe_abstraction/deque.rs

They get a unique name of the form '_N where N is their local def id.
Also: when generating a contract for a safe function, and a parameter of type &mut T has an elided lifetime, and the function's return type has no elided lifetimes, then the full borrow is opened, i.e. instead of requiring the full borrow, we require and ensure the points-to and the OWN of the pointee.

[Rust] Support elided lifetimes

---

src/GNUmakefile
src/frontend/parser.ml
src/rust_frontend/vf_mir_exporter/src/preprocessor.rs
src/rust_frontend/vf_mir_translator/rust_parser.ml
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/tree.rs

This simplifies applying open_full_borrow_strong.
Also:
- Change the syntax of local lifetime declarations from 'let 'a = ...;' to 'let_lft 'a = ...;'
- Allow using 'box' as an identifier
- Add 'make vf' target: makes ../bin/verifast and ../bin/vfide

[Rust] Support local decls in ghost code

---

bin/rust/rust_belt/lifetime_logic.rsspec
src/verifast1.ml
tests/rust/safe_abstraction/box.rs
tests/rust/testsuite.mysh

(I'm not aware of any such official guarantee, but at least for Rust, I guess it follows from Rust's claim of offering the ability to build zero-cost abstractions.)
Also:
- [Rust] Add simplified version of open_full_borrow_strong
- [Rust] Add box.rs example (just deref_mut for now)

Single-field structs have no padding

---

src/SExpressionEmitter.ml
src/explorer/explorer.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
src/verify_expr.ml
tests/rust/safe_abstraction/box.rs

Allows E(?x) or E(_) where E is an arbitrary expression.

Allow patterns as arguments in expression calls

---

src/rust_frontend/rust_fe.ml
src/rust_frontend/vf_mir_exporter/rust-toolchain.toml
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_exporter/src/main.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/purely_unsafe/account_value.rs
tests/rust/purely_unsafe/deque.rs
tests/rust/purely_unsafe/mt_account_transfer.rs
tests/rust/purely_unsafe/point_value.rs
tests/rust/rust-toolchain.toml
tests/rust/safe_abstraction/deque.rs

Also, uses the new '&raw const/mut $expr' syntax instead of
'std::ptr::addr_of!($expr)'/'std::ptr::addr_of_mut!($expr)'.

[Rust] Bump Rust toolchain to nightly-2024-11-23

---

bin/rust/rust_belt/general.rsspec
bin/rust/std/lib.rsspec
src/SExpressionEmitter.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/ast_to_src.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_capnp_alias.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
src/verify_expr.ml
tests/rust/nonnull.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/rc.rs

For each struct S for which the user defines a custom `<S>.own` predicate, and that has non-invariant generic parameters, a proof obligation S_own_mono is now generated, requiring the user to show that the type interpretation satisfies the inferred variance.
Also:
- Generates an `S_upcast` lemma defining upcast::<S<T0...>, S<T1...>>(v)
- Improves VeriFast type inference for pure functions with a generic return type (such as `upcast`)
TODO:
- Verify Rc_own_mono and Arc_own_mono
- Update the S_share_mono proof obligation to also check monotonicity of <S>.share with respect to S's type parameters.

[Rust] Check variance

---

src/rust_frontend/vf_mir_exporter/src/preprocessor.rs

Causes a more helpful message to appear in the Rust frontend crash report when the preprocessor crashes on a nested function.

[Rust] Nested fns: improve crash msg

---

bin/rust/prelude_core_core.rsspec
bin/rust/std/lib.rsspec
tests/rust/safe_abstraction/linked_list.rs

It was unsound. Also, it no longer assumes an Allocator's value does not change.

[Rust] Fix Allocator spec

---

src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/verifast.ml
src/verifast1.ml
src/verify_expr.ml
tests/const_vars.c
testsuite.mysh

VeriFast now produces only a fractional points-to chunk for a `const`-typed local variable.
Fixes #366

Make const vars read-only

---

bin/rust/aliasing.rsspec
bin/rust/prelude.rsspec
bin/rust/prelude_core.rsspec
bin/rust/rust_belt/general.rsspec
bin/rust/rust_belt/lifetime_logic.rsspec
bin/rust/std/lib.rsspec
src/rust_frontend/vf_mir_translator/ast_to_src.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
tests/rust/nonnull.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/deque_i32.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/linked_list.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs

This proof obligation proves that memory referred to by &S references created by unverified typechecked clients is immutable for the lifetime of the shared reference (except for the parts that are under an UnsafeCell).
Proved it for linked_list.rs and generic_pair.rs.
TODO: Prove this proof obligations for the other examples

[Rust] Generate init_ref_S proof obligation

---

src/vfconsole/vfconsole.ml
tests/rust/testsuite.mysh

Verification of Rust programs does not require
a linking step.
It follows that the -c command-line option is
now superfluous for Rust programs.

[Rust] Skip linking step

---

bin/list.gh
src/SExpressionEmitter.ml
src/explorer/explorer.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/verifast.ml
src/verifast1.ml
tests/fixpoint_param_requires_clauses/bad_map1.c
tests/fixpoint_param_requires_clauses/bad_map2.c
tests/fixpoint_param_requires_clauses/bad_map3.c
tests/fixpoint_param_requires_clauses/positive_test.c
testsuite.mysh

Enables recursion through higher-order functions (e.g. a fixpoint function passing itself as an argument to 'map').
Fixes #639

Fixpoint function parameter requires clauses

---

src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/hidden_locals.rs
tests/rust/safe_abstraction/linked_list.rs
tests/rust/testsuite.mysh

More generally enables verification of Rust functions where multiple local variables have the same name.
If, in a Rust function, multiple local variables have the same name X, the corresponding variables after translation are called X, X_1, X_2, etc.
TODO:
- In cases where the variables have nonoverlapping scopes, avoid changing the names.
- TODO: Perhaps ensure that each variable currently called X in the Rust program is also accessible as X in annotations. (For example: a hidden variable X might be accessible as X and as X_0 while not hidden and only as X_0 while hidden.) (A possible approach to achieve this might be by adding support for 'local variable aliases' in the VeriFast engine.)

[Rust] Support hidden locals

---

src/rust_frontend/vf_mir_translator/rust_parser.ml
src/verifast.ml

This preserves the invariant that any lifetime parameter in scope
corresponds to a live lifetime.
Fixes #618

[Rust] let_lft consumes lifetime_token fraction

---

src/GNUmakefile
src/SExpressionEmitter.ml
src/assertions.ml
src/cxx_frontend/decl_translator.ml
src/explorer/explorer.ml
src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/frontend/parser.ml
src/rust_frontend/vf_mir_translator/ast_to_src.ml
src/rust_frontend/vf_mir_translator/rust_parser.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
src/verify_expr.ml

This might be useful for specifying unwind behavior in Rust.

Refactoring: explicitly bind postcond result var

---

bin/rust/std/lib.rsspec
src/verifast1.ml
src/verify_expr.ml
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/struct_layout.rs
tests/rust/testsuite.mysh

VeriFast used to reuse the C logic unchanged, which assumes the first field has offset 0. It now makes no assumptions (except for a struct with just one field).

[Rust] Eliminate unsound struct layout assumption

---

src/verifast.ml
tests/rust/testsuite.mysh
tests/rust/this_pred.rs

Don't crash when 'this' is used in Rust/C

---

examples/busywaiting/flexiblespecs/ticketlock-stronger/cohortlock.c
src/verifast1.ml
tests/rust/safe_abstraction/linked_list.rs
tests/rust/testsuite.mysh

Fixes a bug where recursive fixpoint functions that have type parameters that carry a typeid would not reduce when using Redux because the index of the inductive argument was not reported to Redux correctly.
linked_list.rs now verifies with Redux, in half a second.

Reduce fixpoints with typeid-carrying tparams

---

bin/rust/prelude.rsspec
rust_tutorials/purely_unsafe/solutions/threads.rs
src/assertions.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verify_expr.ml
tests/rust/purely_unsafe/simple_mutex/spec/lib.rsspec
tests/rust/purely_unsafe/simple_mutex/src/lib.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/tree.rs
tests/rust/unverified/platform/spec/lib.rsspec
tests/rust/unverified/sys/spec/lib.rsspec

In Rust, the type of currentThread is now thread_id_t.
Fixes the TODO in the sys::lock spec.

[Rust] thread_token(?_t) &*& _t == currentThread

---

src/verify_expr.ml
tests/rust/purely_unsafe/simple_reverse.rs
tests/rust/testsuite.mysh

Currently the definite nonemptiness analysis happens when a struct object is produced and simply looks for a field of a manifestly nonempty type; in particular, it does not recursively consider the nonemptiness of nested structs or arrays and simply considers them not definitely nonempty.

Produce that definitely nonempty structs live at non-null locations

---

src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
tests/rust/purely_unsafe/arrays.rs

VeriFast now supports array types whose length is a const expression
that refers to const items. VeriFast will currently fully evaluate
the const expression.
(This is probably just a temporary measure. Eventually, to support
verification of code under const generic parameters, we will need
to support non-literal array lengths.)

[Rust] Support const items in array lengths

---

bin/rust/aliasing.rsspec
bin/rust/prelude_core.rsspec
bin/rust/rust_belt/general.rsspec
bin/rust/std/lib.rsspec
docs/rust-reference/src/SUMMARY.md
docs/rust-reference/src/non-unsafe-funcs.md
docs/rust-reference/src/rusts-aliasing-rules.md
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
tests/rust/nonnull.rs
tests/rust/safe_abstraction/arc.rs
tests/rust/safe_abstraction/arc_u32.rs
tests/rust/safe_abstraction/atomic.rs
tests/rust/safe_abstraction/cell.rs
tests/rust/safe_abstraction/cell_u32.rs
tests/rust/safe_abstraction/deque.rs
tests/rust/safe_abstraction/deque_i32.rs
tests/rust/safe_abstraction/generic_pair.rs
tests/rust/safe_abstraction/linked_list.rs
tests/rust/safe_abstraction/mutex.rs
tests/rust/safe_abstraction/mutex_u32.rs
tests/rust/safe_abstraction/rc.rs
tests/rust/safe_abstraction/rc_u32.rs
tests/rust/testsuite.mysh

- **VeriFast accepts atomic.rs with -skip_specless_fns**
- **[Rust] share_full now takes atomic_mask(MaskTop)**
- **Update the VeriFast for Rust Reference**

[Rust] share_full takes atomic_mask(MaskTop); verifying atomic.rs

---

examples/crypto_ccs/crypto_ccs/crypto/identifiers.c
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
tests/rust/public_fields.rs
tests/rust/safe_abstraction/public_fields.rs
tests/rust/testsuite.mysh

Structs with public fields are now allowed. For
pub struct S { f1: T1, f2: T2 }
the following default type predicates are now generated:
pred <S>.own(t, s) = <T1>.own(t, s.f1) &*& <T2>.own(t, s.f2);
pred <S>.share(k, t, l) = pointer_within_limits(&(*l).f1) == true &*& [_]<T1>.share(k, t, &(*l).f1) &*& pointer_within_limits(&(*l).f2) == true &*& [_]<T2>.share(k, t, &(*l).f2);
For now, custom .own or .share type predicates are not supported for structs with public fields.

[Rust] Public fields

---

src/frontend/ast.ml
src/frontend/ocaml_expr_of_ast.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast1.ml
tests/rust/struct_layout.rs

For Rust structs marked as #[repr(C)], VeriFast now assumes the first field is at offset 0, just like it does for C structs.

[Rust] #[repr(C)] structs

---

src/rust_frontend/vf_mir_exporter/src/preprocessor.rs
tests/rust/safe_abstraction/linked_list.rs

The Rust preprocessor no longer crashes when it encounters a
function nested within another function.

[Rust] Don't crash on nested fns

---

src/refinement_checker/main.ml
tests/rust/refinement_checker/identical_verified.rs
tests/rust/refinement_checker/identical_verified_bad.rs
tests/rust/refinement_checker/testsuite.mysh

Apart from functions checked by the function refinement checker, the crate source files and (nested) module source files must be identical after collapsing whitespace.

refinement-checker: check that outside the fns, the files match

---

src/refinement_checker/refinement_checker.ml
src/rust_frontend/vf_mir/vf_mir.capnp
src/rust_frontend/vf_mir_exporter/src/lib.rs
tests/rust/refinement_checker/testsuite.mysh
tests/rust/refinement_checker/unsafety_orig.rs
tests/rust/refinement_checker/unsafety_verified_bad.rs

refinement-checker: check fn `unsafe`ty

---

src/refinement_checker/refinement_checker.ml
tests/rust/refinement_checker/testsuite.mysh
tests/rust/refinement_checker/wrapper_fns_orig.rs
tests/rust/refinement_checker/wrapper_fns_verified0.rs

Extra shared reference creations can only cause the program to have more UB.
Also adds support for generic parameter predicates.

refchecker: allow extra shared ref creations in verified program

---

src/refinement_checker/refinement_checker.ml
tests/rust/refinement_checker/reservation_orig.rs
tests/rust/refinement_checker/reservation_verified.rs
tests/rust/refinement_checker/testsuite.mysh
tests/rust/safe_abstraction/linked_list.rs
tests/rust/safe_abstraction/linked_list/verified/lib.rs
tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
tests/rust/testsuite.mysh

The refinement checker now treats assignments x = &raw mut *x or x = &raw const *x like no-ops (which they are, semantically). Furthermore, it now also allows extra mutable reference creations in the verified program, not just extra shared reference creations.
As a result, refinement-checker now supports pulling apart a function call that involves a reservation of a mutable reference.
This enables verifying LinkedList::split_off_after_node.

refinement-checker: Reservations

---

src/refinement_checker/refinement_checker.ml
tests/rust/refinement_checker/box-deref_orig.rs
tests/rust/refinement_checker/box-deref_verified.rs
tests/rust/refinement_checker/box-ref-deref_orig.rs
tests/rust/refinement_checker/box-ref-deref_verified.rs
tests/rust/refinement_checker/testsuite.mysh

The refinement checker now accepts replacing box deref magic by a Box::as_ptr call.

refinement-checker: Box deref -> Box::as_ptr

---

src/verifast1.ml

Fixes #751.
But: is this sound? See #752.

Allow `float` as pure autolemma parameter

---

tests/rust/safe_abstraction/linked_list/verified/linked_list.rs

Added LinkedList::new to the refinement-checked version of the
linked_list.rs proof.

linked_list.rs: refcheck LinkedList::new

---

bin/rust/std/lib.rsspec
src/refinement_checker/refinement_checker.ml
tests/rust/safe_abstraction/linked_list/verified/linked_list.rs

Added proof of `fn into_element` to the refinement-checked version of the linked_list.rs proof.

[linked_list.rs] Refchecked into_element

---

src/refinement_checker/refinement_checker.ml
src/refinement_checker/stringifier.ml
tests/rust/safe_abstraction/linked_list/verified/linked_list.rs

Also, the refinement checker now dumps the bodies involved when a fn refinement check fails.

linked_list.rs: Refchecked fn `next`

---

bin/rust/std/lib.rsspec
src/refinement_checker/refinement_checker.ml
src/refinement_checker/stringifier.ml
tests/rust/safe_abstraction/btree_node.rs
tests/rust/safe_abstraction/linked_list.rs
tests/rust/safe_abstraction/linked_list/verified/linked_list.rs

Also: in the linked_list.rs proof, functions `pop_front` and
`LinkedList::drop` are safe clients of pop_front_node so do not
need proofs of their own.

[Rust] Fix some Allocator handling kludges

---

.devcontainer/devcontainer.json
setup-build.sh
setup-devcontainer.sh

It was no longer working because
- the GitHub Codespaces base image had grown, causing the devcontainer setup to run out of disk space
- some OPAM packages have been moved to opam-repository-archive

Fix devcontainer setup

---

bin/rust/prelude_core.rsspec
bin/rust/std/lib.rsspec
src/verifast.ml
tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs

Until now, VeriFast would allow a pure autolemma only if all parameter
types were "universal types", defined as being "isomorphic to the SMT
solver universe". Struct types are currently never deemed universal.
From now on, "protected" parameters are exempted from this restriction.
A parameter is protected if the autolemma has a trigger and the
parameter appears in the trigger as an argument to a pure function that
has only typeid-carrying type parameters. If a term matches such a
trigger, the subterm matching the protected parameter is necessarily of
the type of the parameter, despite type erasure.

Allow pure autolemmas with protected parameters

---

bin/rust/prelude.rsspec
tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs

Proved semantic well-typedness of RawVec::{new_in, with_capacity_in, try_reserve, try_reserve_exact}

raw_vec.rs: RawVec safety proofs

---

src/frontend/ast.ml
src/rust_frontend/vf_mir_translator/vf_mir_translator.ml
src/verifast.ml
src/verifast1.ml
tests/rust/safe_abstraction/linked_list/verified/linked_list.rs
tests/rust/safe_abstraction/raw_vec/verified/raw_vec.rs

VeriFast no longer incorrectly considers 'static equivalent with other
lifetimes in predicate type arguments.
Fixes #886.
Also, this commit introduces "inferred type expressions", placeholders
in type expressions to be filled in by the type checker through type
inference. These are not (yet?) exposed to the user but are generated by
the MIR translator as the translation for lifetimes that were erased in
MIR local variable types and function call type arguments. Core VeriFast
currently allows inferred types in local variable types and function
call type arguments.
Furthermore, VeriFast now no longer throws an error when needing to get
the typeid for an inferred type that has not yet been inferred. Instead,
it generates a fresh typeid symbol S. Once the inferred type has been
resolved to a …

[Rust] Fix unify_strict unsoundness #886

---

src/verifast1.ml
src/verify_expr.ml
tests/rust/safe_abstraction/cell.rs

If a Rust expression `p1 == p2` evaluates to `false`, where `p1` and
`p2` are pointers, then we know the pointers are different, but we
also know `ref_origin(p1) != ref_origin(p2)`.
Also:
- cell.rs: Prove init_ref_Cell
- cell.rs: Modernize the proof

[Rust] If p1!=p2, assume ref_origins different

---

.github/workflows/build.yml

This is necessary for using [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions).

Add 'merge_group' trigger to CI workflow

---

src/rust_frontend/vf_mir_exporter/src/lib.rs
tests/rust/const_generic_param.rs
tests/rust/safe_abstraction/raw_vec/verified/Cargo.lock
tests/rust/safe_abstraction/raw_vec/verified/Cargo.toml
tests/rust/testsuite.mysh

The TypingEnv for analyzing types that occur inside a function body needs to include a ConstArgHasType clause for each of the function's const generic parameters.

vf_mir_exporter: Don't crash on const generic params
